BEGIN TRANSACTION;

-- Bestehende Tabellen löschen
DROP TABLE IF EXISTS todo_list;
DROP TABLE IF EXISTS todo;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS angebote;
DROP TABLE IF EXISTS users;

COMMIT;
