DROP TABLE IF EXISTS offer_features;
DROP TABLE IF EXISTS rentals;
DROP TABLE IF EXISTS offers;
DROP TABLE IF EXISTS features;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS region;
